
import { type TeacherAssessment, type StudentResult, type Scenario } from './types';

export const MOCK_TEACHER_ASSESSMENTS: TeacherAssessment[] = [
    {
        id: 'assessment-1',
        uid: 'teacher-mock-uid',
        title: '자기소개 하기',
        topic: '자신에 대해 1분 동안 이야기하기',
        prompt: '자신의 이름, 나이, 취미, 꿈에 대해 영어로 1분 동안 자유롭게 이야기해 보세요.',
        averageScore: 85,
        dateCreated: '2024-05-10',
        assessmentType: 'monologue',
        expectedFormat: '학생은 자신의 개인 정보를 포함하여 간단한 자기소개를 해야 합니다. 시제 사용과 기본 어휘를 평가합니다.',
        recordingTimeLimit: 2,
        createdAt: 1715302800000,
        submissionCount: 1,
    },
    {
        id: 'assessment-2',
        uid: 'teacher-mock-uid',
        title: '가장 좋아하는 음식 주문하기',
        topic: '식당에서 음식 주문하기 시뮬레이션',
        prompt: '당신은 식당에 온 손님입니다. AI 점원에게 가장 좋아하는 음식을 주문해 보세요.',
        averageScore: 92,
        dateCreated: '2024-05-15',
        assessmentType: 'dialogue',
        scenario: 'ordering-food',
        expectedFormat: 'Can I get a... / I would like to order... 와 같은 주문 표현을 정확히 사용해야 합니다. 메뉴에 대한 질문을 할 수 있어야 합니다.',
        createdAt: 1715734800000,
        submissionCount: 1,
    },
    {
        id: 'assessment-3',
        uid: 'teacher-mock-uid',
        title: '주말 계획에 대해 말하기',
        topic: '미래 시제를 사용하여 계획 설명하기',
        prompt: '이번 주말에 무엇을 할 것인지 미래 시제(will, be going to)를 사용하여 설명해 보세요.',
        averageScore: 0,
        dateCreated: '2024-05-20',
        assessmentType: 'monologue',
        expectedFormat: '미래 시제 문장을 3개 이상 포함하여 자신의 계획을 말해야 합니다. 활동과 관련된 동사를 정확히 사용해야 합니다.',
        recordingTimeLimit: 1,
        createdAt: 1716166800000,
        submissionCount: 0,
    },
     {
        id: 'assessment-4',
        uid: 'teacher-mock-uid',
        title: '자유 대화 연습',
        topic: 'AI와 자유롭게 대화하기',
        prompt: 'AI와 자유롭게 영어로 대화해 보세요. 준비가 되면 \'대화 시작\' 버튼을 누르세요.',
        averageScore: 88,
        dateCreated: '2024-05-22',
        assessmentType: 'dialogue',
        scenario: 'free-talk',
        expectedFormat: '학생은 자연스러운 대화에 참여해야 합니다. AI는 유창성, 발음, 어휘, 문법을 전반적으로 평가합니다.',
        createdAt: 1716339600000,
        submissionCount: 1,
    },
];

export const MOCK_STUDENT_RESULTS: StudentResult[] = [
    {
        id: 'result-1',
        studentId: 'student-mock-uid',
        assessmentId: 'assessment-1',
        assessmentTitle: '자기소개 하기',
        name: '이학생',
        avatarUrl: 'https://placehold.co/40x40.png?text=이',
        status: '채점 완료',
        score: 85,
        date: '2024-05-11',
        aiFeedback: '자기소개를 잘 해주었어요! 특히 취미에 대해 이야기할 때 "I like play soccer"라고 했는데, "I like to play soccer" 또는 "I like playing soccer"가 더 자연스러운 표현이에요. 전반적으로 자신감 있는 목소리가 좋았어요!',
        curricularRemarks: '① 자기소개 평가에서 자신의 신상과 취미에 대해 자신감 있게 영어로 표현함. ② 축구를 좋아한다는 표현에서 동사 활용에 약간의 오류가 있었으나, 전달하고자 하는 의미는 명확했음. ③ AI의 피드백을 통해 자신의 오류를 수정하려는 학습 태도가 엿보임.',
        studentFeedbackSummary: '주제는 재미있었지만 1분은 너무 짧게 느껴졌습니다.',
        teacherGuidance: '학생이 동명사와 to부정사의 목적어 활용을 헷갈려 하는 것 같습니다. 관련 문법을 복습하고, 짧은 문장을 만들어보는 연습이 도움이 될 것입니다.',
        studentTranscript: 'Hello, my name is Haksaeng Lee. I am 15 years old. I like play soccer. My dream is to be a scientist.',
        studentRecordingDataUri: 'https://cdn.pixabay.com/audio/2022/11/17/audio_83a21a953e.mp3', // Placeholder audio
        pronunciationScore: 88,
        pronunciationFeedback: '전반적으로 발음이 명확합니다. "soccer"와 "scientist" 단어의 강세를 잘 살려서 말했어요. 다만 "fifteen"의 "f" 발음을 조금 더 명확하게 하면 더 좋을 것 같아요.',
        teacherUid: 'teacher-mock-uid',
        createdAt: 1715389200000,
    },
     {
        id: 'result-2',
        studentId: 'student-mock-uid',
        assessmentId: 'assessment-2',
        assessmentTitle: '가장 좋아하는 음식 주문하기',
        name: '이학생',
        avatarUrl: 'https://placehold.co/40x40.png?text=이',
        status: '채점 완료',
        score: 92,
        date: '2024-05-16',
        aiFeedback: 'AI 점원과의 대화에서 "I would like to order a bulgogi burger."라고 정확하게 주문을 잘 했어요! 질문에도 잘 대답했고, 매우 자연스러운 대화였습니다. 훌륭해요!',
        curricularRemarks: '① 역할극 평가에서 AI 점원에게 정확한 영어 표현을 사용하여 음식을 주문함. ② "I would like to..." 구문을 능숙하게 사용하였으며, 점원의 질문에 막힘없이 대답하는 등 높은 유창성을 보여줌. ③ 상호작용 과제에 자신감을 가지고 적극적으로 참여하는 모습이 인상적임.',
        studentFeedbackSummary: 'AI와 대화하는 것이 재미있었고, 실제 상황처럼 느껴져서 도움이 많이 되었습니다.',
        teacherGuidance: '학생은 정해진 상황에서의 역할극에 강점을 보입니다. 다음 단계로, 돌발 질문을 추가하거나 학생이 먼저 대화를 주도하는 시나리오를 통해 순발력을 길러주는 것도 좋은 방법입니다.',
        studentTranscript: 'AI: Hello, welcome to our restaurant. What would you like to order?\nStudent: Hi, I would like to order a bulgogi burger, please.\nAI: Sure. Anything else for you?\nStudent: No, that will be all. Thank you.',
        studentRecordingDataUri: 'https://cdn.pixabay.com/audio/2022/11/17/audio_83a21a953e.mp3', // Placeholder audio
        pronunciationScore: 95,
        pronunciationFeedback: '발음이 매우 훌륭합니다. 특히 "would like to"와 "burger"의 연음 처리가 자연스럽습니다. 문장 끝의 억양을 조금 더 살리면 훨씬 생동감 있는 표현이 될 거예요.',
        teacherUid: 'teacher-mock-uid',
        createdAt: 1715821200000,
    }
];
